## Case study: oszustwa kart kredytowych - niezbalansowane klasy
https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud
(zalecane użycie metryki AUC)

### Wczytanie i eksploracja danych

In [24]:
import pandas as pd
import numpy as np

In [25]:
data = pd.read_csv("Dane/creditcard.csv")
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [26]:
data.info()  # zbiór nie zawiera braków danych

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [27]:
data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [29]:
print(data.Class.mean())  # klasy są ekstremalnie niezbalansowane

data.Class.value_counts()

0.001727485630620034

0    284315
1       492
Name: Class, dtype: int64

In [53]:
X, y = data.drop(["Class"], axis=1), data["Class"]

### Trenowanie modelu ML

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from xgboost.sklearn import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, cross_val_score

In [72]:
scaler = StandardScaler()
kfold = StratifiedKFold(3, shuffle=True, random_state=123)

model = LogisticRegression(random_state=123)
# model = DecisionTreeClassifier(random_state=123)
# model = RandomForestClassifier(random_state=123)

pipeline = Pipeline([
    ("scaler", scaler),
    ("model", model)
])

cross_val_score(pipeline, X, np.ravel(y), scoring='recall', cv=kfold).mean()
# cross_val_score(pipeline, X, np.ravel(y), scoring='roc_auc', cv=kfold).mean()

0.975318339389379

In [73]:
scaler = StandardScaler()
kfold = StratifiedKFold(3, shuffle=True, random_state=123)

class_weight = {0: 1, 1: 500}  # oversampling
#class_weight = {0: 0.002, 1: 1}  # undersampling

model = LogisticRegression(class_weight=class_weight, random_state=123)
# model = DecisionTreeClassifier(class_weight=class_weight, random_state=123)
# model = RandomForestClassifier(class_weight=class_weight, random_state=123)

pipeline = Pipeline([
    ("scaler", scaler),
    ("model", model)
])

cross_val_score(pipeline, X, np.ravel(y), scoring='recall', cv=kfold).mean()
# cross_val_score(pipeline, X, np.ravel(y), scoring='roc_auc', cv=kfold).mean()

0.979446784870729

## Case study: ekspresja genów - selekcja zmiennych
(zbyt dużo zmiennych dla tak małego zestawu danych)

### Wczytanie i eksploracja danych

In [3]:
import pandas as pd
import numpy as np
import scipy.io

In [47]:
mat = scipy.io.loadmat("Dane/ALLAML.mat")
# print(mat['X'].shape, mat['Y'].shape)

X = pd.DataFrame(mat['X'], columns=["param_" + str(i) for i in range(mat['X'].shape[1])])
y = pd.DataFrame(mat['Y'], columns=["class"]).replace({1: 0, 2: 1})

data = pd.concat([X, y], axis=1)

# data.describe()
data

,param_0,param_1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,param_9,...,param_7120,param_7121,param_7122,param_7123,param_7124,param_7125,param_7126,param_7127,param_7128,class
0,-1.017172,0.074113,-0.406939,-0.905824,-0.341244,-1.077075,0.926511,0.147111,1.922802,0.474334,...,-0.514763,-1.295717,0.019007,-0.064038,0.027578,0.121334,0.588985,-0.388650,-0.159994,0
1,-0.249817,0.906262,0.057617,0.837052,-0.087528,-0.025783,-0.931584,0.227202,0.233942,-0.106453,...,0.551561,-0.277449,0.159027,0.320191,0.003201,-0.043314,0.031879,-0.572969,0.412253,0
2,0.394762,1.155907,-2.436312,1.069436,-1.004181,-1.689219,0.343441,-1.765056,1.408315,-1.378024,...,1.735638,0.511994,-0.564852,1.645782,0.792121,2.290824,0.700407,-0.329348,-0.259515,0
3,-0.208891,0.479786,2.225541,-1.585099,-1.356110,-1.256726,0.782500,-0.623763,-0.347652,-0.295649,...,0.545019,2.628618,-0.549001,-1.466475,-0.340289,-0.648641,-1.327461,-0.492831,-1.503531,0
4,0.087820,0.365365,-0.553640,-0.190798,0.190742,0.746051,0.241580,0.687724,-0.112777,0.676729,...,-0.063374,0.786583,0.322825,0.147288,-1.175747,0.048695,0.098732,-0.605025,0.138569,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,0.538001,-0.393971,0.025016,-0.432119,-0.022052,1.265043,-0.819185,-0.273365,-1.052275,0.007944,...,-0.446073,-0.254567,-0.377277,-0.851708,-0.163004,0.242400,-0.703502,-0.278059,0.884979,1
68,0.578927,-0.591606,0.579223,-0.843259,0.509934,1.105353,-0.074542,0.387384,-0.962799,-1.527621,...,-1.214742,0.546318,-0.062892,0.685209,-0.792367,-1.273338,-0.213248,2.153349,-0.458558,1
69,-0.474907,-0.570802,-0.309138,-0.387430,0.665437,-1.329917,-0.200991,-1.504761,1.016857,-1.078831,...,-0.096084,-0.174478,0.439068,-0.102461,0.063035,0.683077,-0.257816,-0.358198,1.158662,1
70,0.681241,-3.857791,-0.944845,2.159851,-1.986309,-1.995291,-3.418411,-2.505896,1.732666,0.258739,...,1.545924,-1.249952,-0.488237,-1.428052,-0.697076,0.218187,-0.213248,-0.239592,-1.055685,1
71,-0.628378,-1.288531,-0.594391,-1.611912,-0.333060,-0.644581,-1.152870,0.497508,0.960935,-0.594842,...,-0.308694,1.644674,0.624001,0.473883,-0.508710,-0.532418,0.232437,-0.087329,-0.732241,1

In [48]:
print(data.isna().sum().sum())  # zbiór nie zawiera braków danych

data["class"].value_counts()  # klasy "lekko" niezbalansowane

0

0    47
1    25
Name: class, dtype: int64

### Trenowanie modelu ML

In [88]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from xgboost.sklearn import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.feature_selection import SelectFromModel, RFE
from sklearn.preprocessing import StandardScaler

from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, cross_val_score

In [134]:
scaler = StandardScaler()
kfold = StratifiedKFold(5, shuffle=True, random_state=123)

class_weight = {0: 1, 1: 2}

# model = LogisticRegression(class_weight=class_weight, random_state=123)
# model = DecisionTreeClassifier(class_weight=class_weight, random_state=123)
model = RandomForestClassifier(class_weight=class_weight, random_state=123)
# model = XGBClassifier(random_state=123)  # brak ważenia klas!

pipeline = Pipeline([
    ("scaler", scaler),
    ("model", model)
])

cross_val_score(pipeline, X, np.ravel(y), scoring='f1', cv=kfold).mean()

0.9055555555555556

In [136]:
#selector = SelectFromModel(model, threshold=0.01)
selector = RFE(model, n_features_to_select=500, step=100)

pipeline = Pipeline([
    ("selector", selector),
    ("scaler", scaler),
    ("model", model)
])

cross_val_score(pipeline, X, np.ravel(y), scoring='f1', cv=kfold).mean()

0.9333333333333333

## Case study: analiza obrazów - filtrowanie zmiennych
(dane są sztucznie zaszumione przez dodanie niepotrzebnych cech)

### Wczytanie i eksploracja danych

In [1]:
import pandas as pd
import numpy as np
import scipy.io

In [4]:
mat = scipy.io.loadmat("Dane/gisette.mat")
# print(mat['X'].shape, mat['Y'].shape)

X = pd.DataFrame(mat['X'], columns=["p_" + str(i) for i in range(mat['X'].shape[1])])
y = pd.DataFrame(mat['Y'], columns=["class"]).replace({1: 0, -1: 1})

data = pd.concat([X, y], axis=1)

# data.describe()
data

,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,...,p_4991,p_4992,p_4993,p_4994,p_4995,p_4996,p_4997,p_4998,p_4999,class
0,550,0,495,0,0,0,0,976,0,0,...,0,0,991,991,0,0,0,0,983,0
1,0,0,0,0,0,0,0,976,0,0,...,475,0,991,0,0,991,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,742,0,0,0,0,684,0,956,...,0,0,0,0,0,674,0,0,838,0
4,0,0,0,0,0,0,0,608,0,979,...,0,0,828,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,0,511,0,0,0,0,0,0,0,0,...,0,0,852,0,0,0,0,0,0,1
6996,0,0,599,0,0,0,0,910,0,0,...,0,0,0,0,0,0,0,0,707,0
6997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,742,0
6998,0,0,0,0,0,0,0,968,0,0,...,0,0,773,0,0,0,0,0,0,1
6999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,952,0,0,0,1

In [5]:
print(data.isna().sum().sum())  # zbiór nie zawiera braków danych

data["class"].value_counts()  # klasy idealnie zbalansowane

0

0    3500
1    3500
Name: class, dtype: int64

### Trenowanie modelu ML

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from xgboost.sklearn import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.feature_selection import SelectFromModel, RFE, SelectKBest, mutual_info_classif
from sklearn.preprocessing import MinMaxScaler

from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=123)

In [19]:
scaler = MinMaxScaler()

# model = LogisticRegression(random_state=123)
# model = DecisionTreeClassifier(random_state=123)
model = RandomForestClassifier(random_state=123)
# model = XGBClassifier(random_state=123)

pipeline = Pipeline([
    ("scaler", scaler),
    ("model", model)
])

pipeline.fit(X_train, np.ravel(y_train))
y_pred = pipeline.predict(X_test)

accuracy_score(y_test, y_pred)

0.979047619047619

In [23]:
# selector = SelectFromModel(model, threshold=0.001)
selector = RFE(model, n_features_to_select=500, step=100)

pipeline = Pipeline([
    ("selector", selector),
    ("scaler", scaler),
    ("model", model)
])

pipeline.fit(X_train, np.ravel(y_train))
y_pred = pipeline.predict(X_test)

accuracy_score(y_test, y_pred)

0.9714285714285714

In [21]:
feature_filter = SelectKBest(mutual_info_classif, k=2500)

pipeline = Pipeline([
    ("feature_filter", feature_filter),
    ("selector", selector),
    ("model", model)
])

pipeline.fit(X_train, np.ravel(y_train))
y_pred = pipeline.predict(X_test)

accuracy_score(y_test, y_pred)

0.98

## Projekt: Happy Customer Bank
https://discuss.analyticsvidhya.com/t/hackathon-3-x-predict-customer-worth-for-happy-customer-bank/3802

(bardzo dobry zbiór na projekt do portfolio lub końcowy - są różnorodne zmienne, braki danych, niezbalansowane klasy)